#!/bin/bash

jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.1 --no-build
jupyter labextension install @jupyterlab/toc --no-build
jupyter labextension install @lckr/jupyterlab_variableinspector --no-build
jupyter lab build --dev
